#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────
# regenerate.sh — Rebuild shadcn-ui-bundled from latest CLI
# ──────────────────────────────────────────────────────────
#
# What it does:
#   1. Creates a throwaway Vite + React + TS project
#   2. Runs `shadcn init --base=base` + `shadcn add --all`
#   3. Copies components to package/src/
#   4. Rewrites @/ path aliases to relative imports
#   5. Applies known patches (e.g. calendar.tsx)
#   6. Auto-generates barrel export (src/index.ts)
#   7. Syncs runtime dependencies from scaffold → package.json
#   8. Builds both lean + standalone bundles
#   9. Validates the output
#
# Usage:
#   cd <repo-root>
#   ./scripts/regenerate.sh
#
# Requirements:
#   - Node.js 22+, npm
#   - macOS (uses `sed -i ''` syntax — CI runs on macos-latest)
#

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCAFFOLD="$REPO_ROOT/.tmp-scaffold"
DEST="$REPO_ROOT/package/src"
PKG_JSON="$REPO_ROOT/package/package.json"

cleanup() { rm -rf "$SCAFFOLD"; }
trap cleanup EXIT

# ─── Step 1: Create scaffold project ───────────────────────
echo "📦 Step 1/9: Creating Vite + React + TS scaffold..."
rm -rf "$SCAFFOLD"
cd "$REPO_ROOT"
npm create vite@latest .tmp-scaffold -- --template react-ts
cd "$SCAFFOLD"
npm install
npm install -D @tailwindcss/vite

# Configure Vite with @ alias (required by shadcn CLI)
cat > vite.config.ts << 'VITE'
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"
import path from "path"

export default defineConfig({
  plugins: [react(), tailwindcss()],
  resolve: { alias: { "@": path.resolve(__dirname, "./@") } },
})
VITE

# Add path mapping to tsconfig (shadcn reads this)
node -e "
const fs = require('fs');
const cfg = JSON.parse(fs.readFileSync('tsconfig.app.json', 'utf8'));
cfg.compilerOptions.baseUrl = '.';
cfg.compilerOptions.paths = { '@/*': ['./@/*'] };
fs.writeFileSync('tsconfig.app.json', JSON.stringify(cfg, null, 2));
"

# ─── Step 2: Run shadcn CLI ───────────────────────────────
echo "🎨 Step 2/9: Initializing shadcn (base variant)..."
npx shadcn@latest init --base=base --yes --defaults

echo "📥 Step 3/9: Adding all components..."
npx shadcn@latest add --all --yes --overwrite

# ─── Step 3: Copy to package/src ──────────────────────────
echo "🔄 Step 4/9: Copying components to package/src/..."
rm -rf "$DEST/components" "$DEST/hooks" "$DEST/lib"
mkdir -p "$DEST/components/ui" "$DEST/hooks" "$DEST/lib"

cp "$SCAFFOLD/@/components/ui/"*.tsx "$DEST/components/ui/"
cp "$SCAFFOLD/@/hooks/"*.ts "$DEST/hooks/" 2>/dev/null || true
cp "$SCAFFOLD/@/lib/"*.ts "$DEST/lib/"

# ─── Step 4: Rewrite @/ imports ──────────────────────────
echo "✏️  Step 5/9: Rewriting @/ path aliases to relative imports..."

# Components: @/lib/utils → ../../lib/utils
#             @/components/ui/X → ./X
#             @/hooks/X → ../../hooks/X
find "$DEST/components/ui" -name "*.tsx" -exec sed -i '' \
  -e 's|from "@/lib/\([^"]*\)"|from "../../lib/\1"|g' \
  -e 's|from "@/components/ui/\([^"]*\)"|from "./\1"|g' \
  -e 's|from "@/hooks/\([^"]*\)"|from "../../hooks/\1"|g' \
  {} +

# Hooks: @/lib/utils → ../lib/utils
find "$DEST/hooks" -name "*.ts" -exec sed -i '' \
  -e 's|from "@/lib/\([^"]*\)"|from "../lib/\1"|g' \
  {} + 2>/dev/null || true

# Verify no @/ imports remain in source files
if grep -rn 'from "@/' "$DEST/" 2>/dev/null; then
  echo "❌ ERROR: Unrewritten @/ imports found (see above)"
  exit 1
fi
echo "   ✓ All @/ imports rewritten"

# ─── Step 5: Apply patches ───────────────────────────────
echo "🩹 Step 6/9: Applying patches..."

# Patch: react-day-picker v10 ClassNames type uses `month_grid` (not `table`)
# The shadcn CLI generates `table:` but the type requires `month_grid:`
# See: https://github.com/shadcn-ui/ui/issues/XXXX
if grep -q 'table: "w-full border-collapse"' "$DEST/components/ui/calendar.tsx" 2>/dev/null; then
  sed -i '' 's/table: "w-full border-collapse"/month_grid: "w-full border-collapse"/g' \
    "$DEST/components/ui/calendar.tsx"
  echo "   ✓ Patched calendar.tsx (table → month_grid)"
else
  echo "   ○ calendar.tsx patch not needed (already correct or component changed)"
fi

# ─── Step 6: Generate barrel export ──────────────────────
echo "📋 Step 7/9: Generating barrel export (src/index.ts)..."

node -e "
const fs = require('fs');
const path = require('path');

const uiDir = path.join('$DEST', 'components', 'ui');
const hooksDir = path.join('$DEST', 'hooks');
const libDir = path.join('$DEST', 'lib');

const lines = [];
lines.push('// Auto-generated by scripts/regenerate.sh — do not edit manually');
lines.push('');

// Utils
lines.push('// Utils');
for (const f of fs.readdirSync(libDir).filter(f => f.endsWith('.ts')).sort()) {
  const mod = './' + path.join('lib', f.replace(/\.ts$/, ''));
  const code = fs.readFileSync(path.join(libDir, f), 'utf8');
  const exports = [];
  // Named exports: export function X / export const X / export type X
  for (const m of code.matchAll(/export (?:function|const|class) (\w+)/g)) exports.push(m[1]);
  if (exports.length > 0) lines.push('export { ' + exports.join(', ') + ' } from \"' + mod + '\"');
}
lines.push('');

// Hooks
lines.push('// Hooks');
for (const f of fs.readdirSync(hooksDir).filter(f => f.endsWith('.ts')).sort()) {
  const mod = './' + path.join('hooks', f.replace(/\.ts$/, ''));
  const code = fs.readFileSync(path.join(hooksDir, f), 'utf8');
  const exports = [];
  for (const m of code.matchAll(/export (?:function|const|class) (\w+)/g)) exports.push(m[1]);
  if (exports.length > 0) lines.push('export { ' + exports.join(', ') + ' } from \"' + mod + '\"');
}
lines.push('');

// Components
lines.push('// Components');
for (const f of fs.readdirSync(uiDir).filter(f => f.endsWith('.tsx')).sort()) {
  const mod = './' + path.join('components', 'ui', f.replace(/\.tsx$/, ''));
  const code = fs.readFileSync(path.join(uiDir, f), 'utf8');
  
  const namedExports = [];
  const typeExports = [];
  
  // export function X / export const X
  for (const m of code.matchAll(/^export (?:function|const|class) (\w+)/gm)) namedExports.push(m[1]);
  // export { X, Y, Z } at end of file
  for (const m of code.matchAll(/^export \{([^}]+)\}/gm)) {
    for (const name of m[1].split(',').map(s => s.trim()).filter(Boolean)) {
      if (!namedExports.includes(name)) namedExports.push(name);
    }
  }
  // export type { X }
  for (const m of code.matchAll(/^export type \{([^}]+)\}/gm)) {
    for (const name of m[1].split(',').map(s => s.trim()).filter(Boolean)) {
      typeExports.push(name);
    }
  }
  // export type X = ... (standalone type exports)
  for (const m of code.matchAll(/^export type (\w+) =/gm)) {
    typeExports.push(m[1]);
  }
  // export interface X
  for (const m of code.matchAll(/^export interface (\w+)/gm)) {
    typeExports.push(m[1]);
  }
  
  if (namedExports.length > 0) {
    lines.push('export { ' + namedExports.join(', ') + ' } from \"' + mod + '\"');
  }
  if (typeExports.length > 0) {
    lines.push('export type { ' + typeExports.join(', ') + ' } from \"' + mod + '\"');
  }
}

fs.writeFileSync(path.join('$DEST', 'index.ts'), lines.join('\n') + '\n');
const exportCount = lines.filter(l => l.startsWith('export')).length;
console.log('   ✓ Generated index.ts (' + exportCount + ' export lines)');
"

# ─── Step 7: Sync dependencies ───────────────────────────
echo "📦 Step 8/9: Syncing dependencies from scaffold..."

# Read deps from scaffold BEFORE cleanup (trap handles cleanup)
node -e "
const fs = require('fs');
const path = require('path');

const scaffoldPkg = JSON.parse(fs.readFileSync('$SCAFFOLD/package.json', 'utf8'));
const ourPkg = JSON.parse(fs.readFileSync('$PKG_JSON', 'utf8'));

// Collect all external package imports from our source
const srcDir = '$DEST';
const imports = new Set();

function scanDir(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) { scanDir(full); continue; }
    if (!entry.name.match(/\.(ts|tsx)$/)) continue;
    const code = fs.readFileSync(full, 'utf8');
    for (const m of code.matchAll(/from ['\"]([^'\"\.][^'\"]*?)['\"]/g)) {
      // Extract top-level package name
      const imp = m[1];
      const pkg = imp.startsWith('@') 
        ? imp.split('/').slice(0, 2).join('/') 
        : imp.split('/')[0];
      if (pkg !== 'react' && pkg !== 'react-dom') imports.add(pkg);
    }
  }
}
scanDir(srcDir);

// For each import, find the version from scaffold's deps
const scaffoldDeps = { ...scaffoldPkg.dependencies, ...scaffoldPkg.devDependencies };
const newDeps = {};
const missing = [];

for (const pkg of [...imports].sort()) {
  if (scaffoldDeps[pkg]) {
    newDeps[pkg] = scaffoldDeps[pkg];
  } else if (ourPkg.dependencies && ourPkg.dependencies[pkg]) {
    // Keep existing version if scaffold doesn't have it
    newDeps[pkg] = ourPkg.dependencies[pkg];
  } else {
    missing.push(pkg);
  }
}

// Update package.json
ourPkg.dependencies = newDeps;
fs.writeFileSync('$PKG_JSON', JSON.stringify(ourPkg, null, 2) + '\n');

console.log('   ✓ Synced ' + Object.keys(newDeps).length + ' dependencies');
if (missing.length > 0) {
  console.log('   ⚠ Could not resolve versions for: ' + missing.join(', '));
  console.log('   → These may be transitive deps or need manual version pinning');
}
"

# ─── Step 8: Build ───────────────────────────────────────
echo "🏗️  Step 9/9: Building..."
cd "$REPO_ROOT/package"
npm install
npm run build

# ─── Step 9: Validate ────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
COMPONENT_COUNT=$(ls "$DEST/components/ui/"*.tsx | wc -l | tr -d ' ')
EXPORT_LINES=$(grep -c '^export' "$DEST/index.ts")
LEAN_RAW=$(wc -c < dist/index.mjs | awk '{printf "%.1f KB", $1/1024}')
LEAN_GZ=$(gzip -c dist/index.mjs | wc -c | awk '{printf "%.1f KB", $1/1024}')
STANDALONE_RAW=$(wc -c < dist/index.standalone.mjs | awk '{printf "%.1f KB", $1/1024}')
STANDALONE_GZ=$(gzip -c dist/index.standalone.mjs | wc -c | awk '{printf "%.1f KB", $1/1024}')

echo "✅ Build complete!"
echo ""
echo "   Components:  $COMPONENT_COUNT files"
echo "   Exports:     $EXPORT_LINES lines"
echo "   Lean:        $LEAN_RAW ($LEAN_GZ gzipped)"
echo "   Standalone:  $STANDALONE_RAW ($STANDALONE_GZ gzipped)"
echo "   Types:       $(wc -c < dist/index.d.ts | awk '{printf "%.1f KB", $1/1024}')"
echo "   Theme CSS:   $(wc -c < dist/theme.css | awk '{printf "%.1f KB", $1/1024}')"

# Sanity checks
ERRORS=0
if [ ! -f dist/index.mjs ]; then echo "   ❌ Missing dist/index.mjs"; ERRORS=$((ERRORS+1)); fi
if [ ! -f dist/index.standalone.mjs ]; then echo "   ❌ Missing dist/index.standalone.mjs"; ERRORS=$((ERRORS+1)); fi
if [ ! -f dist/index.d.ts ]; then echo "   ❌ Missing dist/index.d.ts"; ERRORS=$((ERRORS+1)); fi
if [ ! -f dist/theme.css ]; then echo "   ❌ Missing dist/theme.css"; ERRORS=$((ERRORS+1)); fi
if grep -q 'ReactSharedInternals' dist/index.standalone.mjs; then echo "   ❌ React internals leaked into standalone bundle"; ERRORS=$((ERRORS+1)); fi
if grep -q '__require("react' dist/index.standalone.mjs; then echo "   ❌ CJS require(\"react\") in standalone bundle"; ERRORS=$((ERRORS+1)); fi
if grep -q 'process\.env' dist/index.standalone.mjs; then echo "   ❌ process.env references in standalone bundle"; ERRORS=$((ERRORS+1)); fi

if [ $ERRORS -eq 0 ]; then
  echo ""
  echo "   ✓ All validation checks passed"
else
  echo ""
  echo "   ❌ $ERRORS validation error(s) — review output above"
  exit 1
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
